### ISSUE TITLE
Update Ruby 2.4.0 => 3.1.0 & Rails 5.1 => 7.0.4

### ISSUE THREAD

**Issue by magnusjak** [elovation/elovation#104]
Any chance of getting this updated so that it works on the current Heroku runtime? 😄
This is more or less exactly what I am looking for, as we have the exact same scenario in my workplace. However, I am not a developer :/ 

Any help would be amazing 💯

**Comment by christoshrousis** [comment]
It's been a while, and it's hard to get an idea of usage stats on this project. Are you using this?

**Comment by magnusjak** [comment]
Hi Christos!

I was planning to, but I couldn't run it because of the old version issue. But I understand why it isn't updated if it's a lot of work.
I was hoping there would be a relatively easy fix.

Regards,
Magnus
________________________________

**Comment by christoshrousis** [comment]
This is being addressed by https://github.com/elovation/elovation/pull/108

**Comment by christoshrousis** [comment]
Resolved by https://github.com/elovation/elovation/pull/108
