### ISSUE TITLE
heroku-postgres's `hobby-dev` plan no longer available

### ISSUE THREAD

**Issue by lluisalemanypuig** [elovation/elovation#105]
I tried setting up elovation in heroku, but it failed due to `hobby-dev` plan no longer available in `heroku-postgres`.

I created a fresh account on December 8th 2022 (I set the necessary payment information for heroku to work) and then I clicked on the button to deploy elovation on heroku. Then, I filled all the necessary information to setup the environment, and received the following error:

    Configure environment
    There was an issue setting up your app environment.
    - invalid app.json
    - The heroku-postgresql:hobby-dev plan is no longer available. Choose a different plan. See all available plans in the Elements Marketplace at elements.heroku.com.

So, I propose the following fixes:
- rewrite the app so that it uses a free addon (I don't know much about Rails development/heroku/... to be more precise, sorry), or
- rewrite the description in the README so that it no longer says that "Elovation can be run on the free tier, so all you will require is a Heroku account to get started with no running costs."

**Comment by christoshrousis** [comment]
Hi @lluisalemanypuig .

Thanks so much for giving Elovation a try.

As you can appreciate, rewriting the app to use a different service is a bit of an undertaking. Heroku only recently got rid of their free tier, and I haven't had a chance to re-write this.

I do have a target in mind, it's called railway, but I haven't had a chance to test if it will be 100% free. From my personal usage of railway, it accepts a credit card but won't bill you until you get some usage. Given the nature of this application I don't think it would require much...

I can easily update the readme now to reflect that it does not run on a free tier of heroku. 

Thanks again.

**Comment by lluisalemanypuig** [comment]
Hello,

Yes, I understand that rewriting the app must be quite a tall order, especially if you can only do this in your free time.

I just wanted to inform you that the free tier is no longer available and at least the readme should change to not be misleading :) I wish I could help more.

Looking forward to new developments of the app!
