### ISSUE TITLE
Create an organization?

### ISSUE THREAD

**Issue by drewolson** [elovation/elovation#57]
I don't currently have enough time or interest to actively maintain elovation. Is there interest in creating an organization?

I'd be happy to add folks like @phillc to the team if there is interest.

**Comment by christoshrousis** [comment]
Hey @drewolson,

It's been a while, but I used this codebase a while back at my last job and was going to start tinking with it again... Think an organization is still plausible?

Christos.

**Comment by drewolson** [comment]
Yes, absolutely. I'll make it an org now and add you. The project is basically dormant at this point.

**Comment by drewolson** [comment]
This is now an organization.
