### ISSUE TITLE
Docker Support

### ISSUE THREAD

**Issue by remingtonc** [elovation/elovation#81]
Hi, any chance of regular installation documentation for a base Linux system? That way we could throw this on Docker Hub too!

**Comment by christoshrousis** [comment]
What steps do I need to take to get it on DockerHub? I'll try sign up later today and see what I can do :)

**Comment by remingtonc** [comment]
@christoshrousis It's just a matter of non-Heroku deployment instructions. For instance, if I wanted to just install it on a basic Linux system, what configuration steps are necessary? All you need to put it on Docker Hub is a Dockerfile with those setup steps and an account. Happy to help here too. Would prefer to host this locally versus on Heroku. :)

**Comment by dragosv** [comment]
Implemented it in https://github.com/dragosv/elovation/tree/docker. It is based on docker compose.

Open pull requests https://github.com/elovation/elovation/pull/82. If anyone can review it and let me know if there is anything I should change/improve that would be appreciated.

**Comment by christoshrousis** [comment]
Thanks again guys. 👍🏼
