### ISSUE TITLE
Docker Compose Issue

### ISSUE THREAD

**Issue by Srutherford2407** [elovation/elovation#86]
Hello I am unable to figure out why my docker-compose up is failing on the Run bundle env.

I am seeing the following error:
```'/usr/local/bundle/bin/bundle:23:in `load': cannot load such file -- /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.17.2/exe/bundle (LoadError)
	from /usr/local/bundle/bin/bundle:23:in `<main>'```

**Comment by Srutherford2407** [comment]
@christoshrousis Is this an issue with my Ruby install? I am on a Mac.

**Comment by christoshrousis** [comment]
Can confirm, I tried to get this running on Ubuntu on a vultr server and I couldn't figure it out. Any chance we can get some documentation on this @dragosv ???

**Comment by dragosv** [comment]
Looking into it. I have it working on Linux.

**Comment by dragosv** [comment]
https://github.com/elovation/elovation/pull/87

**Comment by dragosv** [comment]
@Srutherford2407 The fix was merged.

**Comment by Srutherford2407** [comment]
@dragosv  Thank you very much! I pulled it down late last night and everything appeared to be working. Thanks a lot.

**Comment by christoshrousis** [comment]
Thanks @dragosv I appreciate it, and Thanks @Srutherford2407 for confirming. If you come across anything else please post another issue. 👍
